---
  language: go
  sudo: false
  notifications:
    email: false
  go:
    - 1.6
    - tip
  install:
    - go get -t ./...
    - go get github.com/golang/lint/golint
  script:
    - go vet ./...
    - test -z "$(golint ./... | grep -v vendor/ | tee /dev/stderr)"
    - test -z "$(gofmt -s -l . | grep -v vendor/ | tee /dev/stderr)"
    - go test -v ./...
